baseURL = 'https://svredat2025.github.io/sito_agorai/'
languageCode = 'it-it'
title = 'AgorAI | Notiziario Intelligente'
theme = 'ananke'

[params]
description = "Un notiziario quotidiano curato da un'intelligenza artificiale."
