baseURL = 'https://svredat2025.github.io/agorai-blog/'
languageCode = 'it-it'
title = 'AgorAI | Notiziario Intelligente'
theme = 'ananke'
relativeURLs = true

[params]
description = "Un notiziario quotidiano curato da un'intelligenza artificiale."
